-- seed_fleet_registers.sql — clients, origins & destinations from Daftar Angkut.
-- Safe to re-run (skips existing names).
insert into fleet_clients (name) values
('PT. BERLIAN EKA SAKTI TANGGUH'),
('PT. GUNUNG MAS RAYA'),
('PT. GUNUNG SEJAHTERA IBU PERTIWI'),
('PT. INNO WANGSA'),
('PT. KWALA INTAN SAWIT SELATAN'),
('PT. LONSUM'),
('PT. MERBAUJAYA INDAHRAYA'),
('PT. MITRA NIAGA SEJATI JAYA'),
('PT. MUSIM MAS'),
('PT. MUTIARANUSA AGRO SEJAHTERA'),
('PT. PACIFIC INDOPALM INDUTRIES'),
('PT. PACIFIC MEDAN INDUSTRI'),
('PT. PACIFIC PALMINDO INDUSTRI'),
('PT. PALM TRIMITRA INDOTAMA'),
('PT. SALIM IVOMAS PRATAMA'),
('PT. SARI DUMAI OLEO'),
('PT. SARI DUMAI SEJATI'),
('PT. SAUDARA SEJATI LUHUR'),
('PT. SAWIT MULIA'),
('PT. SINAR PANDAWA'),
('PT. SUMBER SARANA SEKAR SAKTI'),
('PT. SUMBER TANI AGUNG RESOURCE'),
('PT. SUPRA MATRA ABADI'),
('PT. TOLAN TIGA INDONESIA'),
('PT. UMBUL MAS WISESA'),
('PT. UNILEVER OLEOCHEMICAL INDONESIA'),
('PT. YORGO ANUGERAH NUSANTARA')
on conflict (name) do nothing;

insert into fleet_locations (name,kind) values
('BELAWAN','Destination'),
('JAMBI','Destination'),
('PEKAN BARU','Destination'),
('PERKEBUNAN LEMBAH BHAKTI','Both'),
('PKMS PERLABIAN','Origin'),
('PMKS AEK NABARA SELATAN','Origin'),
('PMKS BAHAL','Origin'),
('PMKS DOLOK','Origin'),
('PMKS GUNUNG MELAYU','Origin'),
('PMKS PANGKATAN','Origin'),
('PMKS PERLABIAN','Origin'),
('PMKS SALAPIAN','Origin'),
('PMKS SIBISA MANGATUR','Origin'),
('PMKS TAHUAN GANDA','Origin'),
('PMKS TELUK DALAM','Origin'),
('PMKS TELUK PANJIE','Origin'),
('PMKS TURANGI','Origin'),
('PT. ABDI BUDI MULIA 1','Origin'),
('PT. ABDI BUDI MULIA 2','Origin'),
('PT. ABLE','Destination'),
('PT. ADHITYA SERAYAKORITA','Origin'),
('PT. AGRO JAYA PERDANA','Origin'),
('PT. ANUGRAH LANGKAT MAKMUR','Origin'),
('PT. ASAM JAWA','Origin'),
('PT. ASIAN AGRO AGUNG JAYA','Destination'),
('PT. ASIAN AGRO JAYA','Destination'),
('PT. BARUMUN AGRO SENTOSA','Origin'),
('PT. BELAWAN TANGKI INDONESIA','Destination'),
('PT. BERLIAN EKA SAKTI TANGGUH','Both'),
('PT. BINA RAHMAD MADANI','Origin'),
('PT. BINANGA','Origin'),
('PT. BUMI AGRO PRIMA','Destination'),
('PT. CISADANE SAWIT RAYA','Origin'),
('PT. DOMBA ANGROINTI PRIMA','Destination'),
('PT. DUMAI PARIWARA ABADI','Destination'),
('PT. ENERGI OLEO PERSADA','Destination'),
('PT. FAJAR AGRO SEJAHTERA','Origin'),
('PT. GUNUNG SEJAHTERA IBU PERTIWI','Destination'),
('PT. HARI SAWIT JAYA','Origin'),
('PT. INNO WANGSA','Destination'),
('PT. INTI BENUA PERKASATAMA','Destination'),
('PT. IVOMAS TUNGGAL','Destination'),
('PT. KARYA TANAH SUBUR','Origin'),
('PT. KWALA INTAN SAWIT SELATAN','Origin'),
('PT. MERBAUJAYA INDAH RAYA','Origin'),
('PT. MITRA NIAGA SEJATI JAYA','Origin'),
('PT. MULTIMAS NABATI ASAHAN','Destination'),
('PT. MULTIMAS NABATI ASAHAN - BAAI','Destination'),
('PT. MUSIM MAS','Destination'),
('PT. MUTIARANUSA AGRO SEJAHTERA','Origin'),
('PT. PACIFIC INDOPALM INDUTRIES','Both'),
('PT. PACIFIC MEDAN INDUSTRI','Both'),
('PT. PACIFIC PALMINDO INDUSTRI','Destination'),
('PT. PALM LATEX INDUTRI','Origin'),
('PT. PALM TRIMITRA INDOTAMA','Origin'),
('PT. PERMATA HIJAU PALM OLEO','Both'),
('PT. PRIMANUSA GLOBAL LESTARI','Destination'),
('PT. SALIM IVOMAS PRATAMA','Origin'),
('PT. SALIM IVOMAS PRATAMA - BELAWAN','Destination'),
('PT. SARANA AGRO NUSANTARA','Origin'),
('PT. SARI DUMAI OLEO','Destination'),
('PT. SARI DUMAI SEJATI','Destination'),
('PT. SAUDARA SEJATI LUHUR','Destination'),
('PT. SAWIT MULIA','Origin'),
('PT. SINAR ALAM PERMAI','Destination'),
('PT. SINAR ALAM PERMAI - MARIANA','Destination'),
('PT. SINAR PANDAWA','Origin'),
('PT. SINARLIKA PORTIBI JAYA','Origin'),
('PT. SMART, TBK','Both'),
('PT. TAPIAN NADENGGAN','Destination'),
('PT. TASIK RAJA','Origin'),
('PT. UNILEVER OLEOCHEMICAL INDONESIA','Origin'),
('PT. VVF INDONESIA','Destination'),
('PT. WIRA INNO MAS','Destination'),
('PT. YORGO ANUGERAH NUSANTARA','Both'),
('PTPN IV','Origin'),
('SEI BANGKO','Origin'),
('SEI MANGKEI','Origin'),
('TANGKI TIMBUN BELAWAN','Both'),
('TANGKI TIMBUN LUBUK GAUNG','Destination')
on conflict (name) do nothing;
