-- =========================================================================
-- seed.sql  —  GENERATED by scripts/generate_seed.py. Do not edit by hand.
-- Master data: specialties, drivers, mechanics, trucks, vendors.
-- Spare parts are intentionally excluded from v1.
-- Re-run the generator after changing the source spreadsheet.
-- =========================================================================

begin;

-- Specialties (in-house vs outsourced default is adjustable per work order) ---
insert into specialties (code, name, label, is_outsourced_default) values
  ('SP-01', 'las', 'Tukang Las', false),
  ('SP-02', 'ban', 'Tukang Ban', false),
  ('SP-03', 'mesin', 'Mesin', false),
  ('SP-04', 'gerang', 'Gerang', false),
  ('SP-05', 'kolong', 'Kolong', false),
  ('SP-06', 'posneleng', 'Posneleng', true),
  ('SP-07', 'cabin', 'Cabin', true),
  ('SP-08', 'pom', 'Pom', true),
  ('SP-09', 'dinamo', 'Dinamo', true),
  ('SP-10', 'electrical', 'Electrical', true),
  ('SP-11', 'bubut', 'Bubut', true),
  ('SP-12', 'pres_karet_tingtong', 'Pres Karet Tingtong', true)
on conflict (code) do update set
  name = excluded.name, label = excluded.label,
  is_outsourced_default = excluded.is_outsourced_default;

-- Drivers -----------------------------------------------------------------
insert into drivers (code, name, phone, status) values
  ('D-01', 'SANDI PRANATA', '0822-6730-145', 'Active'::entity_status_person),
  ('D-02', 'WILLY', '0821-6478-0350', 'Active'::entity_status_person),
  ('D-03', 'RUSMAN DANIEL', '0852-7567-3222', 'Active'::entity_status_person),
  ('D-04', 'SYAHRUDDIN', '0813-7043-9492', 'Active'::entity_status_person),
  ('D-05', 'SUDI LASMONO', '0822-1171-6443', 'Active'::entity_status_person),
  ('D-06', 'ADI SOFYAN', '0852-6112-8818', 'Active'::entity_status_person),
  ('D-07', 'BUDIANTO', '0822-7483-0736', 'Active'::entity_status_person),
  ('D-08', 'ARMAN', '0813-2931-069', 'Active'::entity_status_person),
  ('D-09', 'KOKO ENDRI YOFFI', '0853-2067-2397', 'Active'::entity_status_person),
  ('D-10', 'ARDI EGA SETIAWAN', '0822-7414-6271', 'Active'::entity_status_person),
  ('D-11', 'ARMADANI', '0831-3328-3492', 'Active'::entity_status_person),
  ('D-12', 'M.SITORUS', '0813-7602-7460', 'Active'::entity_status_person),
  ('D-13', 'SUHERI', '0813-6234-2181', 'Active'::entity_status_person),
  ('D-14', 'SUTARJO', '0813-6080-8489', 'Active'::entity_status_person),
  ('D-15', 'DOLAT TAHER', '0823-9247-3317', 'Active'::entity_status_person),
  ('D-16', 'MULYONO', '0822-6891-1600', 'Active'::entity_status_person),
  ('D-17', 'SURIADI', '0823-6616-1147', 'Active'::entity_status_person),
  ('D-18', 'ROBINUR', '0813-9787-5082', 'Active'::entity_status_person),
  ('D-19', 'SUGIANTO', '0813-7871-8032', 'Active'::entity_status_person),
  ('D-20', 'ARMIN', '0821-6229-4918', 'Active'::entity_status_person),
  ('D-21', 'SUBUR', '0813-6206-409', 'Active'::entity_status_person),
  ('D-22', 'SUJIONO', '0852-7076-5833', 'Active'::entity_status_person),
  ('D-23', 'NASRUN', '0853-8121-7580', 'Active'::entity_status_person),
  ('D-24', 'GUNAWAN', '0853-6145-0008', 'Active'::entity_status_person),
  ('D-25', 'ISMAIL', '0822-1805-5957', 'Active'::entity_status_person),
  ('D-26', 'JAMALUDDIN', '0821-1507-6601', 'Active'::entity_status_person),
  ('D-27', 'HENDRA IRAWAN', '0853-7355-3339', 'Active'::entity_status_person),
  ('D-28', 'ANWAR', '0812-6388-7635', 'Active'::entity_status_person),
  ('D-29', 'MANUPPAK SINAGA', '0852-6543-2258', 'Active'::entity_status_person),
  ('D-30', 'CANRA SINAGA', '0813-1525-6294', 'Active'::entity_status_person),
  ('D-31', 'RAMLAN', '0822-8743-7499', 'Active'::entity_status_person),
  ('D-32', 'MISWANTO', '0812-2690-5774', 'Active'::entity_status_person)
on conflict (code) do update set
  name = excluded.name, phone = excluded.phone, status = excluded.status;
-- 32 drivers

-- Mechanics ---------------------------------------------------------------
insert into mechanics (code, name, phone, employment_type, can_lift, status) values
  ('M-01', 'DARMANTO', '0823-6037-2241', 'in_house', false, 'Active'::entity_status_person),
  ('M-02', 'INDRA', '0831-6111-2401', 'in_house', false, 'Active'::entity_status_person),
  ('M-03', 'GELENG', '0853-6127-0849', 'in_house', false, 'Active'::entity_status_person),
  ('M-04', 'RONALD', '8022-9912-7680', 'in_house', true, 'Active'::entity_status_person),
  ('M-05', 'RAHMAT', NULL, 'in_house', false, 'Active'::entity_status_person)
on conflict (code) do update set
  name = excluded.name, phone = excluded.phone,
  employment_type = excluded.employment_type, can_lift = excluded.can_lift,
  status = excluded.status;
-- 5 mechanics (incl. new hires)

-- Mechanic -> specialty mapping (primary vs backup proficiency) -----------
insert into mechanic_specialties (mechanic_id, specialty_id, proficiency)
select m.id, s.id, 'primary'::proficiency from mechanics m, specialties s where m.code = 'M-01' and s.name = 'mesin'
union all
select m.id, s.id, 'backup'::proficiency from mechanics m, specialties s where m.code = 'M-01' and s.name = 'kolong'
union all
select m.id, s.id, 'primary'::proficiency from mechanics m, specialties s where m.code = 'M-02' and s.name = 'mesin'
union all
select m.id, s.id, 'backup'::proficiency from mechanics m, specialties s where m.code = 'M-02' and s.name = 'kolong'
union all
select m.id, s.id, 'primary'::proficiency from mechanics m, specialties s where m.code = 'M-03' and s.name = 'kolong'
union all
select m.id, s.id, 'primary'::proficiency from mechanics m, specialties s where m.code = 'M-03' and s.name = 'gerang'
union all
select m.id, s.id, 'primary'::proficiency from mechanics m, specialties s where m.code = 'M-04' and s.name = 'las'
union all
select m.id, s.id, 'primary'::proficiency from mechanics m, specialties s where m.code = 'M-05' and s.name = 'kolong'
on conflict (mechanic_id, specialty_id) do update set
  proficiency = excluded.proficiency;

-- Vendors (needed in v1 for outsourced work orders) -----------------------
insert into vendors (code, name, contact, phone, status) values
  ('V-01', 'AUTO DINAMIKA MAKMUR', NULL, NULL, 'Active'::entity_status_vendor),
  ('V-02', 'BCH', 'AKHUN', '085276989968', 'Active'::entity_status_vendor),
  ('V-03', 'CAHAYA SEMPURNA', 'ALIANG', '085262744969', 'Active'::entity_status_vendor),
  ('V-04', 'CV MEDAN DELI SUPER', 'LISSAN', '08126078008', 'Active'::entity_status_vendor),
  ('V-05', 'DANAU TOBA', 'BUDI', '7341618', 'Active'::entity_status_vendor),
  ('V-06', 'DELI SPRING', 'AHIEN', '08126002530', 'Active'::entity_status_vendor),
  ('V-07', 'DJ', 'ANDY', '085260471100', 'Active'::entity_status_vendor),
  ('V-08', 'EXPRESS', 'ALONG', '0811608080', 'Active'::entity_status_vendor),
  ('V-09', 'OSAKA', 'YANTY', '082164176098', 'Active'::entity_status_vendor),
  ('V-10', 'PALAPA JAYA', 'FANDY', '085297455798', 'Active'::entity_status_vendor),
  ('V-11', 'PELITA', 'EDY', '0812 63488547', 'Active'::entity_status_vendor),
  ('V-12', 'PT ATRIA PRIMA INDONESIA', 'BUDI', '082133793074', 'Active'::entity_status_vendor),
  ('V-13', 'PT AUTO BAN TRADING', 'HARRY', '0811633899', 'Active'::entity_status_vendor),
  ('V-14', 'PT BINTANG TIMUR PRIMA LESTARI', 'WILLY', '08116559056', 'Active'::entity_status_vendor),
  ('V-15', 'PT INDO UTAMA', 'WILLY', '08116559056', 'Active'::entity_status_vendor),
  ('V-16', 'PT MITRA PARTSINDO JAYA', 'AHUI', '081396251339', 'Active'::entity_status_vendor),
  ('V-17', 'PT POLA RAYA JAYA SAKTI', 'YUNI', '0811641498', 'Active'::entity_status_vendor),
  ('V-18', 'PT PRIMASON INDO BARU', 'WILLY', '08116559056', 'Active'::entity_status_vendor),
  ('V-19', 'PT PUTRA AZEZDA PURNAMA', 'LINAH', '085201888988', 'Active'::entity_status_vendor),
  ('V-20', 'PT PUTRA SEJAHTERA MV', NULL, NULL, 'Active'::entity_status_vendor),
  ('V-21', 'PT TIMUR RAYA KARUNIA MULTI', 'SIHOTANG', '08126394113', 'Active'::entity_status_vendor),
  ('V-22', 'SAUDARA BUBUT', 'WAN CHEN', '08126342048', 'Active'::entity_status_vendor),
  ('V-23', 'SAUDARA JAYA', 'ASUN', '085360949620', 'Active'::entity_status_vendor),
  ('V-24', 'SELAMAT MOTOR', 'ANTO', '081361710534', 'Active'::entity_status_vendor),
  ('V-25', 'SINAR ASAHAN', 'SEN HAO', '085103683888', 'Active'::entity_status_vendor),
  ('V-26', 'SINAR LOGAM', 'GONDO', '081263488547', 'Active'::entity_status_vendor),
  ('V-27', 'SUKSES MOTOR', 'APIN', '081375417700', 'Active'::entity_status_vendor),
  ('V-28', 'WIN DIESEL', 'ANTO', '081265528888', 'Active'::entity_status_vendor),
  ('V-29', 'MEDAN DELI SUKSES', NULL, NULL, 'Active'::entity_status_vendor),
  ('V-30', 'CASH', NULL, NULL, 'Active'::entity_status_vendor)
on conflict (name) do update set
  contact = excluded.contact, phone = excluded.phone, status = excluded.status;
-- 30 vendors

-- Trucks (keyed by plate) -------------------------------------------------
insert into trucks (plate, model, fleet_division, status) values
  ('BK 8359 DY', 'MITSUBISHI FN 517 M', 'Gerobak', 'Active'::entity_status_truck),
  ('BK 8361 DY', 'MITSUBISHI FN 517 M', 'Gerobak', 'Active'::entity_status_truck),
  ('BK 8619 DY', 'MITSUBISHI FN 517 M', 'Gerobak', 'Active'::entity_status_truck),
  ('BK 9220 EA', 'MITSUBISHI FN 517 M', 'Gerobak', 'Active'::entity_status_truck),
  ('BK 9223 EA', 'MITSUBISHI FN 517 M', 'Gerobak', 'Active'::entity_status_truck),
  ('BK 9224 EA', 'MITSUBISHI FN 517 M', 'Gerobak', 'Active'::entity_status_truck),
  ('BK 8825 GV', 'MITSUBISHI FN 517 M', 'Gerobak', 'Active'::entity_status_truck),
  ('BK 9226 EA', 'MITSUBISHI FN 517 M', 'Gerobak', 'Active'::entity_status_truck),
  ('BK 9227 EA', 'MITSUBISHI FN 517 M', 'Gerobak', 'Active'::entity_status_truck),
  ('BK 9644 LG', 'MITSUBISHI FN 517 M', 'Gerobak', 'Active'::entity_status_truck),
  ('B 9038 JY', 'NISSAN CD4GV', 'Tangki', 'Active'::entity_status_truck),
  ('B 9400 RU', 'NISSAN CD 450 NN', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8940 LL', 'MITSUBISHI FU 418 U', 'Tangki', 'Active'::entity_status_truck),
  ('B 9653 AK', 'NISSAN CD 54 V', 'Tangki', 'Active'::entity_status_truck),
  ('B 9701 JY', 'NISSAN CD 54 V', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8616 DY', 'MITSUBISHI FN 517 M', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8122 DK', 'NISSAN CDA 12 M DIESEL', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8310 DT', 'MITSUBISHI FM 517 M', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8531 DG', 'MITSUBISHI FN 517 M', 'Tangki', 'Active'::entity_status_truck),
  ('B 9627 AK', 'NISSAN CD 46 V', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8965 FQ', 'NISSAN CD 46 S', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8864 WQ', 'MITSUBISHI FN 527 M', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8071 DW', 'MITSUBISHI FN 527 M', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8178 BM', 'MITSUBISHI FU 419 U', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8573 BE', 'MITSUBISHI FU-418 U', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8670 DZ', 'MITSUBISHI FN 527 M', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8857 DZ', 'MITSUBISHI FN 527 M', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8860 DZ', 'MITSUBISHI FN 527 M', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8309 FB', 'MITSUBISHI FN 527 M', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8530 DC', 'MITSUBISHI FN 527 M', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8726 EW', 'MITSUBISHI FU 418 U', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8687 XH', 'MITSUBISHI FN 517 M', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8393 XH', 'MITSUBISHI FN 517 M', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8515 XG', 'MITSUBISHI FN 517 M', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8236 XF', 'MITSUBISHI FN 517 M', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8455 CF', 'MITSUBISHI FU 418 U', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8302 FC', 'MITSUBISHI FU 418 U', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8607 FI', 'MITSUBISHI FU 418 U', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8327 FC', 'MITSUBISHI FU 418 U', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8235 FC', 'MITSUBISHI FU 418 U', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8582 FC', 'MITSUBISHI FU 418 N-11149', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8438 FC', 'MITSUBISHI FU 418 N-11149', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8505 FC', 'MITSUBISHI FU 418 N', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8501 CF', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8502 CF', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8503 CF', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8504 CF', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8505 CF', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8506 CF', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8009 CG', 'MITSUBISHI FN 517 ML2(6X2) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8010 CG', 'MITSUBISHI FN 517 ML2 (6X2) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8020 CG', 'MITSUBISHI FN 517 ML2 (6X2) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8021 CG', 'MITSUBISHI FN 517 ML2 (6X2) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8001 CP', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8002 CP', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8003 CP', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8004 CP', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8005 CP', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8006 CP', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8822 CP', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8749 CP', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8750 CP', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8751 CP', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8003 CR', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8004 CR', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8006 CR', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8007 CR', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8009 CR', 'MITSUBISHI FN 527 ML (6X4) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8065 CR', 'MITSUBISHI FN 517 ML2 (6X2) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8066 CR', 'MITSUBISHI FN 517 ML2 (6X2) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8067 CR', 'MITSUBISHI FN 517 ML2 (6X2) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8068 CR', 'MITSUBISHI FN 517 ML2 (6X2) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8069 CR', 'MITSUBISHI FN 517 ML2 (6X2) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8070 CR', 'MITSUBISHI FN 517 ML2 (6X2) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8071 CR', 'MITSUBISHI FN 517 ML2 (6X2) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8072 CR', 'MITSUBISHI FN 517 ML2 (6X2) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8073 CR', 'MITSUBISHI FN 517 ML2 (6X2) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 8074 CR', 'MITSUBISHI FN 517 ML2 (6X2) M/T', 'Tangki', 'Active'::entity_status_truck),
  ('BK 1993 ZO', NULL, 'Kantor', 'Active'::entity_status_truck),
  ('BK 1864 JW', NULL, 'Kantor', 'Active'::entity_status_truck),
  ('BK 8403 YL', NULL, 'Kantor', 'Active'::entity_status_truck),
  ('BK 8186 XU', NULL, 'Kantor', 'Active'::entity_status_truck),
  ('BK 1247 QT', NULL, 'Kantor', 'Active'::entity_status_truck),
  ('BK 1993 HE', NULL, 'Kantor', 'Active'::entity_status_truck)
on conflict (plate) do update set
  model = excluded.model, fleet_division = excluded.fleet_division,
  status = excluded.status;
-- 84 trucks

commit;

