#!/usr/bin/env python3
"""
generate_seed.py — regenerate supabase/seed.sql from the Master Database xlsx.

Reads the Drivers, Mechanics, Trucks and Vendors sheets and emits idempotent
INSERT ... ON CONFLICT statements. Specialties and the mechanic->specialty
mapping are defined here in code (they are not in the spreadsheet yet).

Spare Parts are intentionally NOT loaded in v1.

Usage:
    python scripts/generate_seed.py path/to/1_Master_Database.xlsx > supabase/seed.sql
"""
import sys
from openpyxl import load_workbook

# ---------------------------------------------------------------------------
# Static reference data (not in the spreadsheet)
# ---------------------------------------------------------------------------

# code, machine-name, display label, outsourced-by-default?
SPECIALTIES = [
    ("SP-01", "las",                 "Tukang Las",          False),
    ("SP-02", "ban",                 "Tukang Ban",          False),
    ("SP-03", "mesin",               "Mesin",               False),
    ("SP-04", "gerang",              "Gerang",              False),
    ("SP-05", "kolong",              "Kolong",              False),
    ("SP-06", "posneleng",           "Posneleng",           True),
    ("SP-07", "cabin",               "Cabin",               True),
    ("SP-08", "pom",                 "Pom",                 True),
    ("SP-09", "dinamo",              "Dinamo",              True),
    ("SP-10", "electrical",          "Electrical",          True),
    ("SP-11", "bubut",               "Bubut",               True),
    ("SP-12", "pres_karet_tingtong", "Pres Karet Tingtong", True),
]

# Rahmat is new: next ID per the never-reuse rule. Phone unknown for now.
EXTRA_MECHANICS = [
    # code, name, phone, can_lift
    ("M-05", "RAHMAT", None, False),
]

# mechanic-code -> list of (specialty-name, proficiency)
MECHANIC_SPECIALTIES = {
    "M-01": [("mesin", "primary"), ("kolong", "backup")],   # Darmanto
    "M-02": [("mesin", "primary"), ("kolong", "backup")],   # Indra
    "M-03": [("kolong", "primary"), ("gerang", "primary")], # Geleng
    "M-04": [("las", "primary")],                            # Ronald (+ can_lift)
    "M-05": [("kolong", "primary")],                         # Rahmat
}

# mechanics who can help with heavy lifting (capability flag, not a specialty)
CAN_LIFT = {"M-04"}  # Ronald

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def q(val):
    """SQL-quote a value; None -> NULL."""
    if val is None:
        return "NULL"
    s = str(val).strip()
    if s == "":
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def rows(ws, ncols):
    """Yield non-empty data rows (skipping the header) as ncols-length tuples."""
    first = True
    for r in ws.iter_rows(values_only=True):
        if first:
            first = False
            continue
        if r is None:
            continue
        vals = list(r)[:ncols]
        vals += [None] * (ncols - len(vals))
        # skip fully blank rows
        if all(v is None or str(v).strip() == "" for v in vals):
            continue
        yield vals


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(path):
    wb = load_workbook(path, read_only=True, data_only=True)
    out = []
    p = out.append

    p("-- =========================================================================")
    p("-- seed.sql  —  GENERATED by scripts/generate_seed.py. Do not edit by hand.")
    p("-- Master data: specialties, drivers, mechanics, trucks, vendors.")
    p("-- Spare parts are intentionally excluded from v1.")
    p("-- Re-run the generator after changing the source spreadsheet.")
    p("-- =========================================================================")
    p("")
    p("begin;")
    p("")

    # ---- specialties -----------------------------------------------------
    p("-- Specialties (in-house vs outsourced default is adjustable per work order) ---")
    p("insert into specialties (code, name, label, is_outsourced_default) values")
    vals = ",\n".join(
        f"  ({q(c)}, {q(n)}, {q(l)}, {str(o).lower()})" for c, n, l, o in SPECIALTIES
    )
    p(vals)
    p("on conflict (code) do update set")
    p("  name = excluded.name, label = excluded.label,")
    p("  is_outsourced_default = excluded.is_outsourced_default;")
    p("")

    # ---- drivers ---------------------------------------------------------
    p("-- Drivers -----------------------------------------------------------------")
    drv = list(rows(wb["Drivers"], 7))
    p("insert into drivers (code, name, phone, status) values")
    lines = []
    for code, name, phone, status, *_ in drv:
        lines.append(f"  ({q(code)}, {q(name)}, {q(phone)}, {q(status or 'Active')}::entity_status_person)")
    p(",\n".join(lines))
    p("on conflict (code) do update set")
    p("  name = excluded.name, phone = excluded.phone, status = excluded.status;")
    p(f"-- {len(drv)} drivers")
    p("")

    # ---- mechanics -------------------------------------------------------
    p("-- Mechanics ---------------------------------------------------------------")
    mech = list(rows(wb["Mechanics"], 7))
    p("insert into mechanics (code, name, phone, employment_type, can_lift, status) values")
    lines = []
    seen_codes = set()
    for code, name, phone, status, *_ in mech:
        seen_codes.add(code)
        lift = str(code in CAN_LIFT).lower()
        lines.append(
            f"  ({q(code)}, {q(name)}, {q(phone)}, 'in_house', {lift}, {q(status or 'Active')}::entity_status_person)"
        )
    for code, name, phone, can_lift in EXTRA_MECHANICS:
        if code in seen_codes:
            continue
        lines.append(
            f"  ({q(code)}, {q(name)}, {q(phone)}, 'in_house', {str(can_lift).lower()}, 'Active'::entity_status_person)"
        )
    p(",\n".join(lines))
    p("on conflict (code) do update set")
    p("  name = excluded.name, phone = excluded.phone,")
    p("  employment_type = excluded.employment_type, can_lift = excluded.can_lift,")
    p("  status = excluded.status;")
    p(f"-- {len(mech) + len(EXTRA_MECHANICS)} mechanics (incl. new hires)")
    p("")

    # ---- mechanic_specialties -------------------------------------------
    p("-- Mechanic -> specialty mapping (primary vs backup proficiency) -----------")
    p("insert into mechanic_specialties (mechanic_id, specialty_id, proficiency)")
    sel = []
    for mcode, specs in MECHANIC_SPECIALTIES.items():
        for sname, prof in specs:
            sel.append(
                f"select m.id, s.id, {q(prof)}::proficiency "
                f"from mechanics m, specialties s "
                f"where m.code = {q(mcode)} and s.name = {q(sname)}"
            )
    p("\nunion all\n".join(sel))
    p("on conflict (mechanic_id, specialty_id) do update set")
    p("  proficiency = excluded.proficiency;")
    p("")

    # ---- vendors ---------------------------------------------------------
    p("-- Vendors (needed in v1 for outsourced work orders) -----------------------")
    ven = list(rows(wb["Vendors"], 7))
    p("insert into vendors (code, name, contact, phone, status) values")
    lines = []
    for i, (name, contact, phone, status, *_) in enumerate(ven, start=1):
        code = f"V-{i:02d}"
        lines.append(
            f"  ({q(code)}, {q(name)}, {q(contact)}, {q(phone)}, {q(status or 'Active')}::entity_status_vendor)"
        )
    p(",\n".join(lines))
    p("on conflict (name) do update set")
    p("  contact = excluded.contact, phone = excluded.phone, status = excluded.status;")
    p(f"-- {len(ven)} vendors")
    p("")

    # ---- trucks ----------------------------------------------------------
    p("-- Trucks (keyed by plate) -------------------------------------------------")
    trk = list(rows(wb["Trucks"], 7))
    p("insert into trucks (plate, model, fleet_division, status) values")
    lines = []
    for plate, model, fleet, status, *_ in trk:
        lines.append(
            f"  ({q(plate)}, {q(model)}, {q(fleet)}, {q(status or 'Active')}::entity_status_truck)"
        )
    p(",\n".join(lines))
    p("on conflict (plate) do update set")
    p("  model = excluded.model, fleet_division = excluded.fleet_division,")
    p("  status = excluded.status;")
    p(f"-- {len(trk)} trucks")
    p("")

    p("commit;")
    p("")
    print("\n".join(out))


if __name__ == "__main__":
    src = sys.argv[1] if len(sys.argv) > 1 else "1_Master_Database.xlsx"
    main(src)
