-- =========================================================================
-- 0026_tembak_releases.sql — a numbered payout record per release. Each
-- released trip links to its release batch, so a payout can be reprinted and
-- you can see which tembak were paid together and in what order.
-- Run AFTER 0025. Additive.
-- =========================================================================

create table if not exists tembak_releases (
  id            uuid primary key default gen_random_uuid(),
  release_no    bigint generated by default as identity,
  driver_name   text,
  released_date date not null default current_date,
  note          text,
  created_at    timestamptz not null default now()
);

alter table fleet_deliveries add column if not exists tembak_release_id uuid references tembak_releases(id);

do $$
begin
  execute 'alter table tembak_releases enable row level security';
  execute $p$create policy tembak_releases_all on tembak_releases for all using (true) with check (true)$p$;
exception when duplicate_object then null;
end $$;
